[language-server.nixd]
command = "nixd"

[language-server.nixd.formatting]
command = ["nixfmt"]

[language-server.nixd.nixpkgs]
expr = "import (builtins.getFlake \"/etc/nixos\").inputs.nixpkgs { }"

[language-server.nixd.options.nixos]
expr = "(builtins.getFlake \"/etc/nixos\").nixosConfigurations.<HOSTNAME>.options"

[[language]]
name = "nix"
language-servers = [ "nixd" ]
auto-format = true


[language-server.typescript-language-server]
command = "vtsls"
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.typescript-language-server.config.typescript]
updateImportsOnFileMove.enabled = "always"
suggest.completeFunctionCalls = true
tsserver.enableTracing = true
inlayHints.parameterNames.enabled = "all"
inlayHints.parameterTypes.enabled = true
inlayHints.variableTypes.enabled = true
inlayHints.propertyDeclarationTypes.enabled = true
inlayHints.functionLikeReturnTypes = true
inlayHints.enumMemberValues.enabled = true
# format.enable = false
# format.semicolons = "remove"
preferences.importModuleSpecifier = "non-relative"
preferences.importModuleSpecifierEnding = "auto"
# tsserver.pluginPaths = ["typescript-plugin-css-modules", "./node_modules"]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true
